### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by tarcieri** [dtolnay/colorous#1]
This crate looks potentially very interesting for driving color cycling LEDs in `no_std` environments.

A cursory review of the code shows it should basically be "`no_std` ready" by replacing `std` with `core`.

Are you interested in supporting `no_std`?

**Comment by dtolnay** [comment]
I would accept a PR for no_std support.

It's not just replacing `std` with `core` because we do some floating point math (cosines and stuff) that comes from libm and core doesn't have it.

**Comment by tarcieri** [comment]
> I would accept a PR for no_std support.

Cool, I might be interested in working on one.

> we do some floating point math (cosines and stuff)

Aah yes, I've had some fun times with that in the past (I wrote the [micromath](https://github.com/neobirth/micromath) crate).

The `libm` crate works as well, it's just larger/slower. That said, it seems like the `libm` crate changed its API last I looked... it used to have an [`F32Ext`](https://docs.rs/libm/0.1.2/libm/trait.F32Ext.html) trait which made it easy to drop-in in libraries that want to use `libm` in embedded environments or use `std` when available.

Not sure how you feel about a hard dependency there. `micromath` could still function as an optional dependency (where it would take precedence over `std` if you had a `std` feature and both were enabled)

**Comment by dtolnay** [comment]
How about using a low-order polynomial approximation for those functions in the no_std case? We're not launching a rocket here.

**Comment by tarcieri** [comment]
@dtolnay if it's just cosine you need, I can copy and paste the approximation `micromath` uses:

https://github.com/NeoBirth/micromath/blob/develop/src/f32ext/cos.rs

**Comment by dtolnay** [comment]
:+1: That works for me.
