### ISSUE TITLE
Consider publishing on crates.io

### ISSUE THREAD

**Issue by martinfrances107** [dtolnay/colorous#12]
This looks like a really useful module...

In an ideal world, I would like to pull the repo into my own projects via crates.io

I have a few modules publish, so I am failure with the required steps. I think it would take about 20mins

There are some traps in the process... keyword selection for driving traffic to the project is critical and you get only one 
chance to set them .. (no edits ) 

If that is something that you want done.. just let me know and I will create a PR and point to the tutorial pages about
generating keys. (That the owner needs for identification)

I you give me the go ahead I will generate a PR and generate a first draft list of keywords for consideration.

I hope this helps.

**Comment by dtolnay** [comment]
It has been on crates.io for over 3.5 years. It even has keywords. The readme contains a link to the published package page on crates.io, as does the crate-level documentation.

**Comment by martinfrances107** [comment]
opss my mistake
